### PR TITLE
Edit for Paperback Romance school friendly

### PR DESCRIPTION
**Pull request by mrsgcyber**
Edited the text in the PaperbackRomance object to a more school friendly content that avoids suggestive language.   Added bonus of making the female character into the hero of the story.

### CODE REVIEW

**Comment by mprat** [comment]
Thanks for the PR, and sorry for the (extreme) delay in response.

**Comment by mrsgcyber** [comment]
Thanks!  It's my first GitHub contribution but I really love Terminus as a learning tool and want to help.

**Comment by mrsgcyber** [comment]
Do you know when the changed code will go live?  I've been trying it out once a day but still no change. 
Thanks

**Comment by carterjc** [comment]
@mrsgcyber Edits are live at https://www.mprat.org/Terminus/ but not the MIT mirror

**Pull request merged**
